name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: TypeScript check
      run: npx tsc --noEmit
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Check test coverage
      run: |
        echo "Checking test coverage..."
        if [ -f coverage/lcov.info ]; then
          echo "Coverage report generated successfully"
          # You can add coverage thresholds here if needed
        else
          echo "No coverage report found"
          exit 1
        fi
        
    - name: Check package.json
      run: |
        echo "Validating package.json..."
        node -e "
          const pkg = require('./package.json');
          const required = ['name', 'version', 'main', 'module', 'types', 'exports'];
          const missing = required.filter(field => !pkg[field]);
          if (missing.length > 0) {
            console.error('Missing required fields:', missing);
            process.exit(1);
          }
          console.log('✅ Package.json validation passed');
        "
        
    - name: Check build output
      run: |
        npm run build
        echo "Checking build output..."
        if [ ! -d "dist" ]; then
          echo "❌ Build output directory not found"
          exit 1
        fi
        
        # Check for required files
        required_files=("index.js" "index.d.ts" "index.esm.js")
        for file in "${required_files[@]}"; do
          if [ ! -f "dist/$file" ]; then
            echo "❌ Required file not found: dist/$file"
            exit 1
          else
            echo "✅ Found: dist/$file"
          fi
        done
        
    - name: Validate exports
      run: |
        echo "Validating package exports..."
        node -e "
          const pkg = require('./package.json');
          const fs = require('fs');
          
          if (!pkg.exports) {
            console.error('❌ No exports field in package.json');
            process.exit(1);
          }
          
          // Check if all export files exist
          const checkExports = (exports, basePath = '') => {
            for (const [key, value] of Object.entries(exports)) {
              if (typeof value === 'string') {
                const filePath = basePath + value;
                if (!fs.existsSync(filePath)) {
                  console.error('❌ Export file not found:', filePath);
                  process.exit(1);
                }
                console.log('✅ Export file exists:', filePath);
              } else if (typeof value === 'object' && value.import) {
                checkExports(value, basePath);
              }
            }
          };
          
          checkExports(pkg.exports);
          console.log('✅ All exports validated successfully');
        "
